default: &default
  twitter:
    consumer_key: "eIhfMPMasynnFYl22u6zw"
    consumer_secret: "8klw7iwefig17KIclSlQjL55iawfm1WZP7YqQrmyQs"
    callback_url: "http://rails-practice.dev/oauth/callback?provider=twitter"

development:
  <<: *default

test:
  <<: *default

production:
  <<: *default